# fly.toml
app = "portfolio-dashboar"

[build]

[env]
PORT = "8050"

[[services]]
  internal_port = 8050
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
